const constants = {
  GATEWAY_HOST: 'GATEWAY_HOST',
  GATEWAY_HTTP_PORT: 'GATEWAY_HTTP_PORT',
  GATEWAY_TCP_PORT: 'GATEWAY_TCP_PORT',

  MAILER_HOST: 'MAILER_HOST',
  MAILER_TCP_PORT: 'MAILER_TCP_PORT',
  MAILER_SENDER_ADDRESS: 'MAILER_SENDER_ADDRESS',
  MAILER_SENDER_PASSWORD: 'MAILER_SENDER_PASSWORD',

  RMQ_URI: 'RMQ_URI',
  RMQ_MAILER_QUEUE: 'RMQ_MAILER_QUEUE',

  RMQ_SERVICE: 'RMQ_SERVICE',
  MAILER_TCP_CLIENT: 'MAILER_TCP_CLIENT',
  API_GATEWAY_TCP_CLIENT: 'API_GATEWAY_TCP_CLIENT',

  LOCAL: '0.0.0.0',
};

export const {
  GATEWAY_HOST,
  GATEWAY_HTTP_PORT,
  GATEWAY_TCP_PORT,
  MAILER_HOST,
  MAILER_TCP_PORT,
  MAILER_SENDER_ADDRESS,
  MAILER_SENDER_PASSWORD,
  RMQ_URI,
  RMQ_MAILER_QUEUE,
  RMQ_SERVICE,
  MAILER_TCP_CLIENT,
  API_GATEWAY_TCP_CLIENT,
  LOCAL,
} = constants;
